### ISSUE TITLE
Code coverage wtihout unit tests

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_FingerCoaster#1]
Code coverage tracked only by executing the program is not a usable metric. It is often performed in conjunction with unit tests so that the impact of those tests can be measured in a more meaningful way. 

I would either:
- [x] Remove coverage tools completely, or
- [ ] Add unit tests that will be analyzed with coverage tools

**Comment by Emilija100sic** [comment]
I removed coverage tools.
